langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
before_script:
- gem install mailcatcher
- mailcatcher
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
dd:
  secure: 
deploy:
  provider: heroku
  api_key:
    secure: gXh8u2TQKNnrV8AfHXsusDpMcK6NBjI+rDUpkPy9tkyuZdhcUjYER1nUSHhzshwRJ1u1FoG7vbBgOmnhYgH/4SdcWC0dgESAx/2MAXNxwpwWzj9F8s+cAeWeUoUZgLVL+jnvk7qIUMmAABt0/U6zorTBDSuCtW5zi2wwgRTFxD2MdJCuLYZdIYQWfKFMfy7QhI+vGOGy1/VxfL32BMxFNI/5s9Nldt8WCSHXd7QJOcLatVhWALS78pqGSqKk+HWYiPUmHWQy2BO22iKPuDg+yEXKBG7xzNUJcfCHz4YJRAPJ/0UcZpKfabfFC2zJl9UIVsF4Q+ZlPcmRMjY8M7JM8mlmizFHXo0ykuAI/x2rlFi8cRtl1kTwe1c5rjgrCtjQuPQevtrVL0BZl7Bk7oWq35HPd5XaBUOYJPmwnD6dqQMcgRDNNDZo3cVTIc/QSxUrun6VlAakpboc076EYsPNQ8E9zV+gPIlNeUI1Su0//ZaLKD8K6CX6XTnH4mr65Rpdok8bALfbtzKi+yDhVpfbM2A2fhuEAgT4l3rPKprZnHHY/G7DsJ0uhihxYzw+nwH+6WxxeAAloH5GGfM7Y7+NbowjdzgdpYQHkYDpfFz+TOrouL3O3/TeDB8vAlC8njeVw1VkWYO0y8Eix/JFUsT6rjySQEHQAdTUS/ohvB2Lp+k=
  app: steadymind
  on:
    repo: danielbldr/SteadyMind
  skip_cleanup: 'true'
