langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
before_script:
- gem install mailcatcher
- mailcatcher
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
dd:
  secure: 
deploy:
  provider: heroku
  api_key:
    secure: OXgjiDoHlkbp6ExZrcMNZXFdyi3en3F84kLqn6GIGCItAmkPK5odyoh+JVSVkKKPsQHoflhnSRg9alE2bgZV0kJAaUOudFkaPV/oOMjYJNUiwf0uFGzcdcgeK8Tw4AjhbQnGG+XamlM5pkhLE+VLFu2eNVcQcnI7GZiIP0/d5/BHXM70qNCR1xDQVr/bIIUiIMTgAh8hVp8xQU//u8meWx8wFHsodBgM0g2e0dRydOAtYTZMBjepWzV1LRyGZ7Odhg5vhS4GqiN4J9R0Z7oDIy/XUdfqpXdaKG+H91cUFusipL4KLAScifX3ZHXHPGJqZwRdgCqOJaCPaee6jJ0fEKK/8HBlJQtpL4/UcrgV8PBx6lVPad7A1HqrCEm8xzvwEv7ee/R5BuHisZCOP0vr8ZnZ0riOqBKrDwrb8aqKObzoyLUz7KkDcTdzjVh2XjNwTnM0WVYGGuFUkymmRBqlSh9i0Qa0yA11ovNoID4BS+5AU/NBFQE3uUTqwYoY7NqkuX3NWxWDblba1nIRwYLZuAg3PHJJb4LmvcnpmnUA0bD+YNCyQkoismYkZOXPr5iOnSR4wdkVK7rrGfz0FS/yTVVNt1JNBqRNqWiM6QOs6b0qK1dCHdBHmRsHlHy1v4xAkgQ6wZ18l1OgXq5v7NX0bRzQ8hbVHzvaqiYgyD9uMRQ=
  app: steadymind
  on:
    repo: danielbldr/SteadyMind
  skip_cleanup: 'true'
