langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
before_script:
- gem install mailcatcher
- mailcatcher
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
dd:
  secure: 
deploy:
  provider: heroku
  api_key:
    secure: fHCZip5ELhKP1ea+feosNzatNkKNZtymm1iK2P+KHnYgPyvQ0vb/7rWpzwQo0q4tdZBIF0uRa7VfIS+YdWvCKVdRBrUB/mYaADxjpErq++RYd2L54yp0G6l01LxD8zQKg9f9fSvrDj1VWQrMUqmHaT+/C5fByzrd75AxQCi92+8qoSO6y5/fXc/x/OfGfecNVrXZnIxzcfsujyp9WuSNxy/Gxi9jb6czgSOlxUsC7ONzTJYybxCZXjET3Ns+z2hdJav5hQsIlDveIMUzfwNw6iioIKa4XoXHkBAlWWKqPSYTXR0UtduEA5I0hjw3eoCtMeXZFN0LPLS2eugJ3xeWqG6rOJoDNIF/D08PL/oCrrEb0mf8G0o16zo1BSZJQNK85T/JxGp1kiM6xJugDElbF2DKjRa97PonlFY3moFQuXo8SljuUJryXbZYjvIjauTf6CpHdg83apVQbpx+8X6Ro2vJTccFoBu44LmPZWl5Ly0hhyUpYRcN9AuUz0H7xjis9Z8/BbjEk7Fh9+0bCBqSNxOOhQbPNTWuO6PcWuP5ySAVrfANMwaNxhnOvJ6JEiYMUXE5AWH37NdUsVApUIz+VwnLPn4oKOrSmhloxpk7IeiNw+SPp8lSc3zh5VuJ+sf8G/LogTEvVOTwRzKA2aPYHvsDJZDLBdmr77SVzbq/kEY=
  app: steadymind
  on:
    repo: danielbldr/SteadyMind
  skip_cleanup: 'true'
