langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
before_script:
- gem install mailcatcher
- mailcatcher
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
dd:
  secure: 
deploy:
  provider: heroku
  api_key:
    secure: yLqQZQdMActvGF+LKBjrNLlXRwtKgwtVSU93qdb6TSqeUxnuXNpsrmY2w/Q2Ft/BIP/xGWFa3wOeXK10XhNmDLiBhR1H1YXQbu7AjoLx5jn1flshuXHEcEmcVrCL39V/k+XbhRMdEys0b8I8hNno/V3Mfq7AfgmO4XlTrR0bhhPWn6/dCz0VtQd7qTDT+8WGx7/zcRFBvEIMxClGmB1hwfyZ6hVFVDogn6iItBpHk42H7KzkpBpzFNG5ubkSuzkHPhp2siIvYkNT8XnelPRTB1WZs/uWWsxh+4I/qmj+q4bGCM7G/TiNP9/uGySF1MU1E6T3f55O3uE62MqILk0Tdxhl2Kg61f0M0SRVYEmogvO9TZ2OBwZa8UeYDa6059ayEzLKzot8c4zhbtwQqIgOvW8jQBX58DQEdbNe50aox6B1Maf9MnarMxYddCTCaWtSfXdvllIWlES8HMHCxNDw3oppk1aRKYKKNiMW/fsMv1XDehWX1UwcKQbcSFZd6c5dAfceGwWr+Nu8a2QG9H1YFn4dT6xnN3b0XshMWzXzFNlj+uOKqk2+LMQ6LqRZWWnUOKN8ZnWMMhZQpedImSzAN8bxg/U2Ia4Lko5sIoYZmRxjcU46e+z8LzmuMktIrzoXyIiKJgKDiXMJ9WC6ehR+EykmwaxM0iYmqHBviJu3QGs=
  app: steadymind
  run: rails db:migrate
