langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
before_script:
- gem install mailcatcher
- mailcatcher
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
dd:
  secure: 
deploy:
  provider: heroku
  api_key:
    secure: qVmwK/NPxoWVW84ZmSWlJt5RHo0wlvZnlnAzw0QHvuyvZxeDqYgqyIA/gtAybdCk913vAQSeatsIxBSyHB4g5bxw1eV+JX3RVtL5MnuLLkn+Ba6DQabvO/kM8QJkrrDg2cYB/qTAt0f+d4yluK/fuHLQoQL1Jyx8rAXOflvjzVhcyYxWGjQXlJJaOSh6BkXtT7N6owgfS0fqbYb6ErL/aL0Qte1mwk/vKrx6ZR7lb9/PIdXV6aYEVzT0IjCqzg1upSmDBvoG2WHSQrPf6EXxyGXODPy3WfLFznXRLByJoTtAYGmZoQfWug1ByWSBwgPeN0TSiyXPrNeBHdo64awlFOXtTdvIWHhZlZqcohZAXjC+bKDlrh8zdMoDnkDmA3bBNJBQ2cMa1SeuAkydojdBpTA2+ddfDeDqWeqJwSfvmiG3Z3ENd3XnZs6hj/C1Q6eQhBu/h0Dr9mNbA7EE3C+ExtwfM59kAMQwKJU1OOaiXpuG+3KCeOXrN4ndlWXg61gzqQ3tk61mxL3bafr3J2bw7BoGMdV4zat9j16VuXZAhd2Euyh6GoGXc6WK0UovdwkmOg0VFeKhHizgQ70+kE/lT426erTdbWaWkWcV225UN8C0xmqEfcESDCw09OsvUtPoyutKh0/YQYA0nqeeFJ1sgM7y2UBQorZrx7CYtBDOF1Q=
  app: steadymind
  on:
    repo: danielbldr/SteadyMind
  skip_cleanup: 'true'
