langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- yes | gem update --system --force
- gem install bundler
before_script:
- gem install mailcatcher
- mailcatcher
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
dd:
  secure: 
deploy:
  provider: heroku
  api_key:
    secure: mvMVUFx1tPJzW93gxTxeK26QsvBtgCr+07Yj9kaTm2rW/W6SjyeERcFq4PoFnq6Z5tSVdpaifNLnkyB5qa/X99OQbJKNrCOHbqCr+TZAWzmxowTEihfAOty+C9C6SRm5MHtc9lpTBH/583dI1zj3U/B3JKs/OIsVNrl0iPxrd/1sBqowaLo+EX16lDocFkaWizVsMlM6CslSmPdVmmIYuFTKrmV1fUR4wN87nYuBbQBt053Sdjs7q0XqswOYXxrBM+7dMy/aby6SVMqjkxvzWgprSTMU08hG3fWSzb/nhyPHUWmJo19zVHrxotB7G6zzO7F6rKAAC0Wl4kSNM1LhlrwJIhmXpLBzDENEqIbvPJkMYOF6dwAvqO7+D8ee/SAHYamE+Us0Fflr7RA5ZS0Yy4r5yJJUdJAf7ch+n4ICPYtuCCMNffw08Ltcd2jDeeT6i4WGFHt2dI/PlRkZE8huvHeysnbc1/E6DJkXtN1mJSOTI4+b9gik3LdF94YTHUonE3mp1HRYUq7tgcVPOnAcTFoGta5/C9mi2dWLeSure+OKwAGbRJvIbsLqL8db3dHbKXPPIfXxcu4YXwowTIiEpYWipHT2k1PrfRx0DeXXLOOsJbeV4mKCFe4WX1b2x+FTXdkQJE9YQ/TCeu9hHsjLaVhILNRNaiWfLYnQA2obw0I=
  app: steadymind
  on:
    repo: danielbldr/SteadyMind
  skip_cleanup: 'true'
